#old_sound_rabbit_mq:
#    connections:
#        default:
#            url: '%env(RABBITMQ_URL)%'
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer

qubit_mq:
    sandbox: true
    producer:
        module: 'USER' # nombre de modulo, va a ser univoco por la aplicacion que use el bundle
#    consumers:
# Se ejecutan los consumers como: php bin/console rabbitmq:consumer -m 10 nombre_consumer
#        sas: # nombre del consumer
#            name: 'TEST' #'cola que va a rexibir mensajes' #UNA SOLA
#            handler:
#                - {name: TEST.TEST.TEST, service: AppBundle\Service\Handler\TestHandler}
#                - {name: TEST.TEST.TEST2, service: AppBundle\Service\Handler\Test2Handler}
#                - {name: sas.login.billing, service: servicio_billing}