# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $stopwatch: '@?debug.stopwatch'
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\:
        resource: '../src/Service'
        public: true

#    app.request_listener:
#        class: App\EventSubscriber\ContextSubscriber
#        tags:
#            - { name: kernel.event_listener, event: kernel.request }
#        arguments:
#            - '@app.context.handler'
#
#    app.response_listener:
#        class: App\EventSubscriber\ContextSubscriber
#        tags:
#            - { name: kernel.event_listener, event: kernel.response }
#        arguments:
#            - '@app.context.handler'
#
#    app.context.handler:
#        class: App\Classes\ContextHandler
#        public: true

    App\Classes\:
        resource: '../src/Classes'
        public: true

    App\Service\CacheManagerFactory:
        class: Qubit\Bundle\UtilsBundle\Factory\CacheManagerFactory
        public: true
        arguments:
            - '%env(CACHE_TYPE)%'
            - '%env(CACHE_DSN)%'
#            - 'redis'
#            - 'redis://127.0.0.1:6379'

    App\Cache\UserCache:
        factory:   'App\Service\CacheManagerFactory:cacheManager'
        arguments: ['app.user']

    App\Cache\AuthCache:
            factory:   'App\Service\CacheManagerFactory:cacheManager'
            arguments: ['app.auth']

    App\Cache\AuthExtraCache:
            factory:   'App\Service\CacheManagerFactory:cacheManager'
            arguments: ['app.auth_extra']

    App\Service\AuthService:
        class: App\Service\AuthService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@App\Cache\AuthCache'
            - '@monolog.logger.auth'

    App\Service\UserService:
        class: App\Service\UserService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@App\Cache\UserCache'
            - '@monolog.logger.user'

    App\Service\AuthExtraService:
        class: App\Service\AuthExtraService
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@App\Cache\AuthExtraCache'
            - '@monolog.logger.auth_extra'